config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contacts, only: %i(new create)

  root 'contacts#new'
end

app/models/user.rb
# Devise user model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
# Contact form controller
class ContactsController < ApplicationController
  def new
    @contact_form = ContactBuilder.new(current_user).contact
  end

  def create
    @contact_form = Contact.new contact_params

    if @contact_form.valid?
      ContactMailer.contact_email(@contact_form.name,
                                  @contact_form.message,
                                  @contact_form.email).deliver_later

      flash[:notice] = 'Your contacts was sent by email'
      redirect_to new_contact_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit :name, :email, :message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.slim
= content_for :title, 'Send your contact data'

= simple_form_for @contact_form, url: contacts_path do |f|
  = f.input :name, input_html: { required: true }
  = f.input :email, input_html: { required: true }, as: :email
  = f.input :message
  = f.submit 'Submit'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li
    = link_to 'Sign Out', destroy_user_session_path, method: :delete
- else
  li
    = link_to 'Sign In', new_user_session_path
  li
    = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html

  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]

    title
      = content_for?(:title) ? yield(:title) : 'Contact Form'

    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Contact Form'}"
    == csrf_meta_tags
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true

  body
    header
      == render 'layouts/navigation'

    main[role="main"]
      .container
        == render 'layouts/messages'

        header.gap
          h1 = content_for?(:title) ? yield(:title) : 'Contact Form'
          hr

        == yield

    == javascript_include_tag 'application', 'data-turbolinks-track' => true